### ISSUE TITLE
readable matcher fails to stop the execution

### ISSUE THREAD

**Issue by piotrturski** [RokLenarcic/AhoCorasick#49]
when reading very long stream and finally tell the matcher to end the matching, program still continues to work.

that's because the line:
https://github.com/RokLenarcic/AhoCorasick/blob/aeb614a58f118b51e295de5c74b116a966a32e9a/src/main/java/com/roklenarcic/util/strings/AhoCorasickMap.java#L241

escapes from the `buf.hasRemaining()` loop but not from the `haystack.read(buf) != -1` and more data can still wait on the pipe but not in the char buffer

**Comment by RokLenarcic** [comment]
You are probably correct, I'll have to fix all of the versions.
